name: aptiprep
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^7.1.1
  firebase_auth: ^5.7.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  dotted_border: ^2.0.0
  file_picker: ^10.2.0
  firebase_core: ^3.15.2
  firebase_analytics: ^11.5.2
  linkedin_login: ^3.1.3
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.10
  http: ^1.4.0
  html_unescape: ^2.0.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  firebase_app_check: ^0.3.2+10
  webview_flutter: ^4.9.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  camera: ^0.11.2
  path_provider: ^2.1.5
  path: ^1.9.1
  google_generative_ai: ^0.4.7
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:  # ✅ Moved outside the flutter block
  android: true
  ios: true
  image_path: "assets/logo/playstore.png"  # ✅ Make sure this file exists and is square (512x512)

flutter:
  uses-material-design: true

  assets:
    - assets/images/PracticeSite.jpg
    - assets/images/LearningModules.jpg
    - assets/images/StudyPlans.jpg
    - assets/images/brain.jpg
    - assets/images/AptiPrep.png
    - assets/images/prit.jpg
    - assets/images/test.jpg
    - assets/images/ai.jpg
    - assets/icons/google.png
    - assets/icons/linkedin.png
    - assets/avatar/  
    - assets/icons/
    - assets/logo/playstore.png
    
