// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvejbFAFiEwn88QaG8wfgDZWCh7U6MhvM',
    appId: '1:940695030332:web:765c7de002376265ca9139',
    messagingSenderId: '940695030332',
    projectId: 'application-4cf18',
    authDomain: 'application-4cf18.firebaseapp.com',
    storageBucket: 'application-4cf18.appspot.com',
    databaseURL: 'https://application-4cf18-default-rtdb.firebaseio.com',

    measurementId: 'G-ZXL3QLT52T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2j-mL8aig0BEakgjwmq_zqbpOcE1zAqo',
    appId: '1:940695030332:android:62f85f6771f46c97ca9139',
    messagingSenderId: '940695030332',
    projectId: 'application-4cf18',
    storageBucket: 'application-4cf18.appspot.com',
    androidClientId:
        '940695030332-4l6reauj9mfh7pqi7ltdvdqmqrat07si.apps.googleusercontent.com',
    databaseURL: 'https://application-4cf18-default-rtdb.firebaseio.com',
    measurementId: 'G-ZXL3QLT52T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7vhGtsG4xfDb2ulSxqYtHzupzQef2Jc',
    appId: '1:940695030332:ios:927632368a8bbfe7ca9139',
    messagingSenderId: '940695030332',
    projectId: 'application-4cf18',
    storageBucket: 'application-4cf18.appspot.com',
    androidClientId:
        '940695030332-4l6reauj9mfh7pqi7ltdvdqmqrat07si.apps.googleusercontent.com',
    iosClientId:
        '940695030332-b281absic12k1ou2lsescq7lhuhtn5ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptiprepFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb7vhGtsG4xfDb2ulSxqYtHzupzQef2Jc',
    appId: '1:940695030332:ios:927632368a8bbfe7ca9139',
    messagingSenderId: '940695030332',
    projectId: 'application-4cf18',
    storageBucket: 'application-4cf18.appspot.com',
    androidClientId:
        '940695030332-4l6reauj9mfh7pqi7ltdvdqmqrat07si.apps.googleusercontent.com',
    iosClientId:
        '940695030332-b281absic12k1ou2lsescq7lhuhtn5ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptiprepFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvejbFAFiEwn88QaG8wfgDZWCh7U6MhvM',
    appId: '1:940695030332:web:39c542e971bf902aca9139',
    messagingSenderId: '940695030332',
    projectId: 'application-4cf18',
    authDomain: 'application-4cf18.firebaseapp.com',
    storageBucket: 'application-4cf18.firebasestorage.app',
    measurementId: 'G-WDNZNPZQNF',
  );
}
